name = "queuest"
compatibility_date = "2025-06-17"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[[kv_namespaces]]
binding = "SHARE_KV"
id = "678c9e3f2c01496ea4e7bec5a2ef4ffe"

[[d1_databases]]
binding = "DB"
database_name = "queuest-db"
database_id = "84d447c9-fcbf-4ff3-ac32-90a28a7dd668"
migrations_dir = "migrations"
